services:
  app:
    container_name: app_invest_helper_bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: postgres_invest_helper_bot
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_invest_helper_bot
    restart: always

volumes:
  postgres-db: